version: '3'

services:
  drill-admin:
    image: drill4j/admin:0.7.0-95
    environment:
      - TEST2CODE_PLUGIN_VERSION=0.7.0-126
      - LOG_LEVEL=INFO
    ports:
      - 8090:8090

  admin-ui:
    image: drill4j/admin-ui:0.7.0-267
    ports:
      - 8091:8080
